version: '3.7'

networks:
  kong-net:

services:
  #---------------------------------------------------------------------------------
  # Kong : The API Gateway
  #---------------------------------------------------------------------------------
  kong-gateway:
    image: kong:2.7.0-alpine
    container_name: kong-gateway
    networks:
      - kong-net
    volumes:
      - ./kong-configuration/kong_declarative_conf.yml:/usr/local/kong/declarative/kong.yml
      - ./kong-configuration/kong.conf:/etc/kong/kong.conf
    environment:
        KONG_DATABASE: "off"
        KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
        # KONG_LOG_LEVEL: "debug"
        # KONG_PROXY_ACCESS_LOG: logs/access.log
        # KONG_ADMIN_ACCESS_LOG: logs/admin_access.log
        # KONG_PROXY_ERROR_LOG: logs/error.log 
        # KONG_ADMIN_ERROR_LOG: logs/error.log 
        # KONG_STATUS_ACCESS_LOG: "on"
        KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8100:8100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong-gateway:8001"]
      interval: 5s
      timeout: 2s
      retries: 15