version: '3.7'

networks:
  kong-net:

services:
  #######################################
  # Kong : The API Gateway
  #######################################
  kong-gateway:
    build: ./kong-build
    image: kong-custom-plugin
    container_name: kong-gateway
    networks:
      - kong-net
    volumes:
      - ./kong-configuration/kong_declarative_conf.yml:/usr/local/kong/declarative/kong.yml
    environment:
        KONG_DATABASE: "off"
        KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
        KONG_PROXY_ACCESS_LOG: /dev/stdout
        KONG_ADMIN_ACCESS_LOG: /dev/stdout
        KONG_PROXY_ERROR_LOG: /dev/stderr
        KONG_ADMIN_ERROR_LOG: /dev/stderr
        KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
        KONG_GO_PLUGINS_DIR: "/tmp/go-plugins" #Important !!!!!! don't miss
        KONG_PLUGINS: "key-checker" #Important !!!!!! don't miss
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8100:8100
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://kong-gateway:8001"]
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 5