
SELECT NOW();

CREATE DATABASE db_konga WITH OWNER = konguser ENCODING = 'UTF8' CONNECTION LIMIT = -1;

CREATE USER konga_adm WITH ENCRYPTED PASSWORD 'konga_adm';

GRANT ALL PRIVILEGES ON DATABASE db_konga TO konga_adm;
