version: '3.7'

networks:
  kong-net:

volumes:
  kong_database:

services:
  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    networks:
      - kong-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - kong_database:/var/lib/postgresql/data

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong/kong-gateway:2.8.0.0-alpine
    container_name: kong-migration
    entrypoint: sh -c "sleep 10 && kong migrations bootstrap -v"
    networks:
      - kong-net
    restart: on-failure
    environment:
        KONG_PG_HOST: kong-database #container link name
        KONG_PG_DATABASE: ${POSTGRES_DB_NAME}
        KONG_PG_USER: ${POSTGRES_USER}
        KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Kong : The API Gateway
  #######################################
  kong-gateway:
    #image: kong:latest
    image: kong/kong-gateway:2.8.0.0-alpine
    container_name: kong-gateway
    networks:
      - kong-net
    volumes:
      - ./kong-conf/certs/domain/kong-apigw.local.net.crt:/home/kong/kong-apigw.local.net.crt
      - ./kong-conf/certs/domain/kong-apigw.local.net.key:/home/kong/kong-apigw.local.net.key
      - ./kong-conf/kong.conf:/etc/kong/kong.conf
    environment:
        KONG_DATABASE: postgres #Type of database
        KONG_PG_HOST: kong-database #container link name
        KONG_PG_DATABASE: ${POSTGRES_DB_NAME}
        KONG_PG_USER: ${POSTGRES_USER}
        KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}
        KONG_PROXY_ACCESS_LOG: ${KONG_PROXY_ACCESS_LOG}
        KONG_ADMIN_ACCESS_LOG: ${KONG_ADMIN_ACCESS_LOG}
        KONG_PROXY_ERROR_LOG: ${KONG_PROXY_ERROR_LOG}
        KONG_ADMIN_ERROR_LOG: ${KONG_ADMIN_ERROR_LOG}
        KONG_ADMIN_LISTEN: ${KONG_ADMIN_LISTEN}
        KONG_ADMIN_GUI_URL: http://localhost:8002
        KONG_SSL_CERT: /home/kong/kong-apigw.local.net.crt
        KONG_SSL_CERT_KEY: /home/kong/kong-apigw.local.net.key
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8002:8002
      - 8444:8444
      - 8100:8100
    links:
      - kong-database
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong-gateway:8001"]
      interval: 5s
      timeout: 2s
      retries: 15