version: '3.7'

networks:
  kong-net:

services:
  #######################################
  # Kong : The API Gateway
  #######################################
  kong-gateway:
    image: kong:latest
    #image: kong:2.1.3
    container_name: kong-gateway
    networks:
      - kong-net
    volumes:
      - ./kong-configuration/kong_declarative_conf.yml:/usr/local/kong/declarative/kong.yml
    environment:
        KONG_DATABASE: "off"
        KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
        KONG_PROXY_ACCESS_LOG: /dev/stdout
        KONG_ADMIN_ACCESS_LOG: /dev/stdout
        KONG_PROXY_ERROR_LOG: /dev/stderr
        KONG_ADMIN_ERROR_LOG: /dev/stderr
        KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    restart: always
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 8100:8100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong-gateway:8001"]
      interval: 5s
      timeout: 2s
      retries: 15